spring.security.user.name=admin
spring.security.user.password=secret
spring.datasource.url=jdbc:mysql://localhost:8081/flowers_db
spring.datasource.username=flowershop
spring.datasource.password=flowers
spring.active.profiles=demo