name: Build, Test, deploy on render and Push Docker Image
permissions:
  contents: write
  packages: write

on:
  workflow_run:
    workflows: ["pull request pipeline"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Trigger Render deploy
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          ref: ${{  github.ref_name }}

